server:
  port: 80
  tomcat:
    max-connections: 1000
  
spring:
  freemarker:
    suffix: .ftl
    content-type: text/html; charset=utf-8
    cache: false
    template-loader-path:
    - classpath:/templates 
    
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/product?useUnicode=true&characterEncoding=UTF-8&useverifyServerCertificate=false&useSSL=false
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
    
  redis:
    host: 127.0.0.1
    port: 16379
    database: 1
    password: Ddc@2018
    jedis:
      pool:
        max-active: 100
        min-idle: 10
        max-idle: 100
        max-wait: 1000ms
    
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.lizp.sec.cache.entity
  configuration:
    map-underscore-to-camel-case: true
    
    
    
    
    
